### ISSUE TITLE
support django 1.11 (deprecation of MIDDLEWARE_CLASSES)

### ISSUE THREAD

**Issue by sdementen** [django-fiber/django-fiber#252]
For django > 1.10, the middleware should probably use the  django.utils.deprecation.MiddlewareMixin mixin (https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-middleware) as MIDDLEWARE_CLASSES are deprecated, correct ?

**Comment by richardbarran** [comment]
[The code has already been updated](https://github.com/django-fiber/django-fiber/commit/acea9a0ef893bddfd8ec526dd701b62a455982bc) but we probably need a new release :-)
I'll open a ticket so that we think about a new release and Django 1.11 support.
