### ISSUE TITLE
Make sure objects is the default manager

### ISSUE THREAD

**Issue by ramonakira** [django-fiber/django-fiber#258]
Hi,

I don't mean to nag but I would really appreciate if https://github.com/django-fiber/django-fiber/pull/257/commits/1e0a08cf279ab37c0ced6c7d5f02294c0fe67f08 could be merged in a new subrelease. Otherwise makemigrations makes bogus migrations inside the django-fiber directory, preventing doing any serious work.

Thanks in advance!

**Comment by richardbarran** [comment]
Hi @ramonakira - apologies, I am overflowing with work at the moment. It will be a few weeks before I can look at django-fiber. Maybe one of the other maintainers can help?

**Comment by jaap3** [comment]
I just released version 1.4.1 with both the managers and upload settings fixes
