### ISSUE TITLE
Fiber errors out on admin page when running on Django 2.1

### ISSUE THREAD

**Issue by alito** [django-fiber/django-fiber#264]
Like lots of other apps, fiber runs into the 
```
render() got an unexpected keyword argument 'renderer'
```
error message when adding a new page in the admin section when Django is upgraded to 2.1. The issue is that every widget must now take a ```renderer``` parameter.

**Comment by richardbarran** [comment]
Fixed in PR #266 - thanks for the pointing out the issue.
