### ISSUE TITLE
Upgrade or pin django-mptt 

### ISSUE THREAD

**Issue by ramonakira** [django-fiber/django-fiber#268]
With version 0.10.0 of django-mptt out and django-fiber specifying `django-mptt>=0.9.1`, version 0.10.0 wil get installed, triggering the need for migrations.

We should either pin django-mptt to < 0.10.0 or upgrade to 0.10.0. Keep in mind that, according to the [changelog](https://github.com/django-mptt/django-mptt/blob/master/docs/upgrade.rst) of django-mptt, they're dropping support for Python 2.7.

**Comment by richardbarran** [comment]
FWIW I'd vote for the "quick and ugly" fix :-)
Just pin to < 0.10.0 and do a micro-release - and leave a note in the requirements file so that next time we do a full release of django-fiber we'll remember to upgrade django-mptt and do these migrations.

**Comment by ramonakira** [comment]
Allright, i've created a PR: https://github.com/django-fiber/django-fiber/pull/269

**Comment by richardbarran** [comment]
I've merged your PR and released version 1.6.1.
