### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by jaap3** [django-fiber/django-fiber#271]
I tried to get Fiber's test suite to pass on Django 3.0 but am unable to because the required version of django-mptt uses `django.utils.six` which has been dropped in Django 3.0.

The only way forward seems to be to start using django-mptt >= 0.10. However, this would also require us to drop Python 2 support. Are we ready to take this step?

**Comment by dbunskoek** [comment]
LGTM, let the next version of fiber be compatible with Python 3.6+/Django2.2+ only. And make sure to document that django-fiber 1.6 is the last version compatible with Python 2.

**Comment by jaap3** [comment]
After upgrading `django-mptt` `easy-thumbnails` started raising errors because `django.utils.six` is now missing. Sadly, a Django 3.0 compatible version has yet to be released (See also: https://github.com/SmileyChris/easy-thumbnails/issues/524)

**Comment by jaap3** [comment]
`easy-thumbnails` is now Django 3.0 compatible thanks to https://github.com/SmileyChris/easy-thumbnails/pull/533, just waiting for a release.

Same goes for `django-compressor` and `djangorestframework` these packages also have a (official) Django 3.0 compatible version in the works (The current version of DRF seems to work fine in Django 3.0).

Once these are released we should be almost ready to release a new version.

**Comment by richardbarran** [comment]
Jaap3's PR #275 is ready to go and brings Django 3 support - so this ticket can be closed.
