### ISSUE TITLE
The link on the README to the Django Fiber screencast on vimeo is broken.

### ISSUE THREAD

**Issue by favour-olumese** [django-fiber/django-fiber#294]
![django-fiber_on_vimeo](https://user-images.githubusercontent.com/70489864/187044858-620f89d1-5915-4743-9f25-f125079f33db.PNG)

**Comment by richardbarran** [comment]
Thanks for noticing this - I've fixed the link.

**Comment by favour-olumese** [comment]
> Thanks for noticing this - I've fixed the link.

@richardbarran You are welcome. I also noticed that the analytics image on the readme is broken.

**Comment by richardbarran** [comment]
Analytics image - well spotted, thank you.
